// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ietgplhyurvswlijjnfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldGdwbGh5dXJ2c3dsaWpqbmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTQwMDUsImV4cCI6MjA1NjM5MDAwNX0.CsOh_ck-VBmHKiVmEFpYFzS7TG7wC2iA-kl9M7e6Y8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);